export function flipCoin() {
  return Math.random() < 0.5;
}

export function pickRandomArrayElement<T>(array: T[]): T {
  return array[getRandomInt(0, array.length - 1)];
}

// Pulled from here: https://stackoverflow.com/a/1527820
export function getRandomInt(min: number, max: number) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

// Pulled from here: https://stackoverflow.com/a/48083382
export function shuffleArray<T>(array: T[]): T[] {
  let currentIndex = array.length,
    randomIndex;

  while (currentIndex != 0) {
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;

    [array[currentIndex], array[randomIndex]] = [
      array[randomIndex],
      array[currentIndex],
    ];
  }

  return array;
}

// Generated by Copilot
// In this function, min and max define the range of numbers, and bias controls 
// the bias towards lower numbers. A bias greater than 1 will make lower numbers 
// more likely, while a bias less than 1 will make higher numbers more likely. 
// A bias of 1 will give a uniform distribution.
export function biasedRandom(min: number, max: number, bias: number): number {
  // Generate a random number between 0 and 1, raise it to the power of the bias
  const random = Math.pow(Math.random(), bias);
  // Scale the number to the desired range and round down to get an integer
  const scaled = Math.floor(random * (max - min + 1)) + min;
  return scaled;
}

// Pulled from here: https://stackoverflow.com/a/49434653
export function randomBoxMuller(min: number, max: number, skew: number = 1) {
  let u = 0,
    v = 0;
  while (u === 0) u = Math.random(); //Converting [0,1) to (0,1)
  while (v === 0) v = Math.random();
  let num = Math.sqrt(-2.0 * Math.log(u)) * Math.cos(2.0 * Math.PI * v);

  num = num / 10.0 + 0.5; // Translate to 0 -> 1
  if (num > 1 || num < 0)
    num = randomBoxMuller(min, max, skew); // resample between 0 and 1 if out of range
  else {
    num = Math.pow(num, skew); // Skew
    num *= max - min; // Stretch to fill range
    num += min; // offset to min
  }
  return num;
}
